using NetworkTrafficGuard.Core.Localization;

namespace NetworkTrafficGuard.Tray.Localization;

public static class UiTextProvider
{
    public static IReadOnlyList<UiCultureOption> CultureOptions { get; } =
    [
        new(SupportedCultures.TraditionalChinese, "繁體中文"),
        new(SupportedCultures.SimplifiedChinese, "简体中文"),
        new(SupportedCultures.Japanese, "日本語"),
        new(SupportedCultures.English, "English")
    ];

    public static UiText Get(string? cultureName)
    {
        var culture = SupportedCultures.GetCultureOrDefault(cultureName).Name;

        return culture switch
        {
            SupportedCultures.SimplifiedChinese => SimplifiedChinese,
            SupportedCultures.Japanese => Japanese,
            SupportedCultures.English => English,
            _ => TraditionalChinese
        };
    }

    private static UiText TraditionalChinese { get; } = new()
    {
        Settings = "設定",
        ShowWindow = "顯示",
        ExitApplication = "結束",
        AppTitle = "網路狀態",
        WifiLabel = "Wi-Fi",
        SimRouterLineLabel = "其他連線",
        PriorityTitle = "連線優先順序",
        MoveUp = "上移",
        MoveDown = "下移",
        ShowColumn = "顯示",
        AlertColumn = "警示",
        PriorityColumn = "優先",
        NetworkColumn = "網路",
        GatewayColumn = "閘道",
        InterfaceColumn = "介面",
        TypeColumn = "類型",
        RealtimeTraffic = "即時流量",
        SettingsTitle = "自訂名稱設定",
        SettingsDescription = "設定偵測到的網路顯示名稱與控制權限。",
        ExistingNetworkColumn = "偵測到的網路",
        DisplayNameColumn = "顯示名稱",
        LanguageLabel = "語言",
        AllowAdapterChanges = "允許變更 Wi-Fi 介面狀態（需要系統管理員權限）",
        AllowRouteChanges = "允許變更路由優先順序（需要系統管理員權限）",
        AlertSettingsTitle = "警示設定",
        AlertThresholdLabel = "警示門檻",
        AlertThresholdUnit = "Kbps",
        Save = "儲存",
        Cancel = "取消",
        InUse = "使用中",
        Available = "可用",
        Connected = "已連線",
        NotConnected = "未連線",
        Disabled = "已停用",
        NotPresent = "不存在",
        Unknown = "未知",
        Updating = "更新中",
        InterfaceFormat = "介面 #{0}",
        GatewayNotDetected = "未偵測到閘道",
        NoPrimaryLine = "目前沒有主要連線",
        PrimaryLineFormat = "主要連線：{0}",
        AdapterEnabledNotice = "Wi-Fi 控制已啟用，執行時需要系統管理員權限。",
        AdapterDryRunNotice = "Wi-Fi 控制為模擬模式，不會變更系統設定。",
        SettingsSaved = "設定已儲存。",
        RouteIdle = "尚未調整優先順序。",
        RoutePrioritySaved = "優先順序已儲存。系統設定未變更。",
        RoutePriorityApplied = "優先順序已儲存，並已送出系統套用。",
        RoutePriorityApplyFailedFormat = "優先順序已儲存，系統套用失敗：{0}",
        NameSavedNotice = "顯示名稱已儲存。",
        EnableAction = "啟用",
        DisableAction = "停用",
        WifiUpdatingFormat = "{0} Wi-Fi 中...",
        AdapterStateMismatchFormat = "{0} Wi-Fi 指令已送出，目前介面狀態為 {1}。",
        TrafficAlertTitle = "網路流量異常",
        TrafficAlertMessageFormat = "{0} 的即時流量已達 {1}，超過警示門檻 {2} Kbps。",
        AlertEnabledNoticeFormat = "已啟用警示：{0}（門檻 {1} Kbps）。",
        AlertDisabledNoticeFormat = "已停用警示：{0}。"
    };

    private static UiText SimplifiedChinese { get; } = TraditionalChinese with
    {
        Settings = "设置",
        ShowWindow = "显示",
        ExitApplication = "退出",
        AppTitle = "网络状态",
        SimRouterLineLabel = "其他连接",
        PriorityTitle = "连接优先顺序",
        MoveUp = "上移",
        MoveDown = "下移",
        ShowColumn = "显示",
        AlertColumn = "警示",
        PriorityColumn = "优先",
        NetworkColumn = "网络",
        GatewayColumn = "网关",
        InterfaceColumn = "接口",
        TypeColumn = "类型",
        SettingsTitle = "自定义名称设置",
        SettingsDescription = "设置检测到的网络显示名称与控制权限。",
        ExistingNetworkColumn = "检测到的网络",
        DisplayNameColumn = "显示名称",
        LanguageLabel = "语言",
        AllowAdapterChanges = "允许变更 Wi-Fi 接口状态（需要管理员权限）",
        AllowRouteChanges = "允许变更路由优先顺序（需要管理员权限）",
        AlertSettingsTitle = "警示设置",
        AlertThresholdLabel = "警示阈值",
        AlertThresholdUnit = "Kbps",
        Save = "保存",
        Cancel = "取消",
        Available = "可用",
        Connected = "已连接",
        NotConnected = "未连接",
        Disabled = "已禁用",
        NotPresent = "不存在",
        Unknown = "未知",
        Updating = "更新中",
        InterfaceFormat = "接口 #{0}",
        GatewayNotDetected = "未检测到网关",
        NoPrimaryLine = "当前没有主要连接",
        PrimaryLineFormat = "主要连接：{0}",
        AdapterEnabledNotice = "Wi-Fi 控制已启用，执行时需要管理员权限。",
        AdapterDryRunNotice = "Wi-Fi 控制为模拟模式，不会变更系统设置。",
        SettingsSaved = "设置已保存。",
        RouteIdle = "尚未调整优先顺序。",
        RoutePrioritySaved = "优先顺序已保存。系统设置未变更。",
        RoutePriorityApplied = "优先顺序已保存，并已发送系统套用。",
        RoutePriorityApplyFailedFormat = "优先顺序已保存，系统套用失败：{0}",
        NameSavedNotice = "显示名称已保存。",
        EnableAction = "启用",
        DisableAction = "停用",
        AdapterStateMismatchFormat = "{0} Wi-Fi 指令已发送，当前接口状态为 {1}。",
        TrafficAlertTitle = "网络流量异常",
        TrafficAlertMessageFormat = "{0} 的实时流量已达到 {1}，超过警示阈值 {2} Kbps。",
        AlertEnabledNoticeFormat = "已启用警示：{0}（阈值 {1} Kbps）。",
        AlertDisabledNoticeFormat = "已停用警示：{0}。"
    };

    private static UiText Japanese { get; } = TraditionalChinese with
    {
        Settings = "設定",
        ShowWindow = "表示",
        ExitApplication = "終了",
        AppTitle = "ネットワーク状態",
        SimRouterLineLabel = "その他の接続",
        PriorityTitle = "接続の優先順位",
        MoveUp = "上へ",
        MoveDown = "下へ",
        ShowColumn = "表示",
        AlertColumn = "警告",
        PriorityColumn = "優先",
        NetworkColumn = "ネットワーク",
        GatewayColumn = "ゲートウェイ",
        InterfaceColumn = "インターフェイス",
        TypeColumn = "種類",
        RealtimeTraffic = "リアルタイム通信量",
        SettingsTitle = "表示名設定",
        SettingsDescription = "検出されたネットワークの表示名と制御権限を設定します。",
        ExistingNetworkColumn = "検出されたネットワーク",
        DisplayNameColumn = "表示名",
        LanguageLabel = "言語",
        AllowAdapterChanges = "Wi-Fi インターフェイスの状態変更を許可する（管理者権限が必要）",
        AllowRouteChanges = "ルート優先順位の変更を許可する（管理者権限が必要）",
        AlertSettingsTitle = "警告設定",
        AlertThresholdLabel = "警告しきい値",
        AlertThresholdUnit = "Kbps",
        Save = "保存",
        Cancel = "キャンセル",
        InUse = "使用中",
        Available = "利用可能",
        Connected = "接続済み",
        NotConnected = "未接続",
        Disabled = "無効",
        NotPresent = "存在しません",
        Unknown = "不明",
        Updating = "更新中",
        InterfaceFormat = "インターフェイス #{0}",
        GatewayNotDetected = "ゲートウェイ未検出",
        NoPrimaryLine = "現在の主要接続はありません",
        PrimaryLineFormat = "主要接続: {0}",
        AdapterEnabledNotice = "Wi-Fi 制御は有効です。実行時に管理者権限が必要です。",
        AdapterDryRunNotice = "Wi-Fi 制御はシミュレーションモードです。システム設定は変更されません。",
        SettingsSaved = "設定を保存しました。",
        RouteIdle = "優先順位はまだ変更されていません。",
        RoutePrioritySaved = "優先順位を保存しました。システム設定は変更されていません。",
        RoutePriorityApplied = "優先順位を保存し、システムへの適用を送信しました。",
        RoutePriorityApplyFailedFormat = "優先順位を保存しましたが、システムへの適用に失敗しました: {0}",
        NameSavedNotice = "表示名を保存しました。",
        EnableAction = "有効化",
        DisableAction = "無効化",
        WifiUpdatingFormat = "Wi-Fi を{0}しています...",
        AdapterStateMismatchFormat = "Wi-Fi の{0}コマンドを送信しました。現在の状態は {1} です。",
        TrafficAlertTitle = "ネットワーク通信量の異常",
        TrafficAlertMessageFormat = "{0} のリアルタイム通信量が {1} に達し、警告しきい値 {2} Kbps を超えました。",
        AlertEnabledNoticeFormat = "警告を有効にしました: {0}（しきい値 {1} Kbps）。",
        AlertDisabledNoticeFormat = "警告を無効にしました: {0}。"
    };

    private static UiText English { get; } = TraditionalChinese with
    {
        Settings = "Settings",
        ShowWindow = "Show",
        ExitApplication = "Exit",
        AppTitle = "Network Status",
        SimRouterLineLabel = "Other Connection",
        PriorityTitle = "Connection Priority",
        MoveUp = "Move Up",
        MoveDown = "Move Down",
        ShowColumn = "Show",
        AlertColumn = "Alert",
        PriorityColumn = "Priority",
        NetworkColumn = "Network",
        GatewayColumn = "Gateway",
        InterfaceColumn = "Interface",
        TypeColumn = "Type",
        RealtimeTraffic = "Realtime Traffic",
        SettingsTitle = "Custom Name Settings",
        SettingsDescription = "Configure display names and control permissions for detected networks.",
        ExistingNetworkColumn = "Detected Network",
        DisplayNameColumn = "Display Name",
        LanguageLabel = "Language",
        AllowAdapterChanges = "Allow Wi-Fi interface changes (administrator permission required)",
        AllowRouteChanges = "Allow route priority changes (administrator permission required)",
        AlertSettingsTitle = "Alert Settings",
        AlertThresholdLabel = "Alert threshold",
        AlertThresholdUnit = "Kbps",
        Save = "Save",
        Cancel = "Cancel",
        InUse = "In Use",
        Available = "Available",
        Connected = "Connected",
        NotConnected = "Disconnected",
        Disabled = "Disabled",
        NotPresent = "Not Present",
        Unknown = "Unknown",
        Updating = "Updating",
        InterfaceFormat = "Interface #{0}",
        GatewayNotDetected = "Gateway not detected",
        NoPrimaryLine = "No primary connection",
        PrimaryLineFormat = "Primary connection: {0}",
        AdapterEnabledNotice = "Wi-Fi control is enabled and requires administrator permission.",
        AdapterDryRunNotice = "Wi-Fi control is in simulation mode and will not change system settings.",
        SettingsSaved = "Settings saved.",
        RouteIdle = "No priority changes yet.",
        RoutePrioritySaved = "Priority order saved. System settings were not changed.",
        RoutePriorityApplied = "Priority order saved and sent to the system.",
        RoutePriorityApplyFailedFormat = "Priority order saved, but system apply failed: {0}",
        NameSavedNotice = "Display name saved.",
        EnableAction = "Enabling",
        DisableAction = "Disabling",
        WifiUpdatingFormat = "{0} Wi-Fi...",
        AdapterStateMismatchFormat = "{0} Wi-Fi command was sent. Current interface state is {1}.",
        TrafficAlertTitle = "Network Traffic Alert",
        TrafficAlertMessageFormat = "{0} realtime traffic reached {1}, exceeding the alert threshold of {2} Kbps.",
        AlertEnabledNoticeFormat = "Alert enabled: {0} (threshold {1} Kbps).",
        AlertDisabledNoticeFormat = "Alert disabled: {0}."
    };
}
